from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
index = (root / 'preview-next' / 'index.html').read_text(encoding='utf-8')
app = (root / 'preview-next' / 'app.js').read_text(encoding='utf-8')
router = (root / 'preview-next' / 'router-fix.js').read_text(encoding='utf-8')

errors = []

def require(condition, message):
    if not condition:
        errors.append(message)

require('<script src="app.js"></script><script src="router-fix.js"></script>' in index,
        'router-fix.js must load immediately after app.js')
require("const INTERNAL_PREFIX = '?page=';" in router,
        'router must intercept the legacy query-string route prefix')
require("document.addEventListener('click'" in router,
        'router must use delegated click handling for dynamically rendered links')
require("rawHref.startsWith(INTERNAL_PREFIX)" in router,
        'router must intercept ?page= links')
require("history.pushState" in router and "history.replaceState" in router,
        'router must update browser history without server navigation')
require("window.addEventListener('popstate'" in router,
        'router must support browser Back/Forward')
require("window.addEventListener('hashchange'" in router,
        'router must restore hash routes')
require("location.search.includes('page=')" in router,
        'router must migrate existing query links instead of dropping to Home')
require("toHashHref" in router and "href=\"${toHashHref(id)}\"" in router,
        'top navigation must be rebuilt with stable hash routes')

# Every page target generated by the app must be a route the renderer understands.
page_targets = set(re.findall(r"\$\{P\}([a-zA-Z0-9_-]+)", app))
page_targets.update(re.findall(r"\$\{P\+([a-zA-Z0-9_\.\[\]]+)\}", app))

known_literals = {
    'home', 'cup', 'traditions', 'processing', 'chemistry', 'tools',
    'sensory', 'culinary', 'vocabulary', 'biology', 'engere', 'kuti',
    'chemo', 'kawa'
}

# Explicit literal route links in generated HTML.
literal_routes = set(re.findall(r"\$\{P\}([a-z][a-z0-9_-]*)", app))
unknown = sorted(literal_routes - known_literals)
require(not unknown, f'unknown literal preview route(s): {unknown}')

# Ensure the fallback is only for truly unknown route ids.
require("else html=home()" in app,
        'app fallback contract changed; review router validation')
require("else if(traditionData[page])" in app and "else if(generic[page])" in app,
        'app must retain tradition and generic route families')

if errors:
    print('PREVIEW NAVIGATION AUDIT: FAIL')
    for error in errors:
        print(f'- {error}')
    raise SystemExit(1)

print('PREVIEW NAVIGATION AUDIT: PASS')
print('Verified stable client-side routing, route restoration, and legacy-query migration.')
